# Generated by Django 4.0.6 on 2022-07-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='TipoSeguro',
        ),
    ]
