# Generated by Django 4.0.6 on 2022-08-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ordemservico_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='relatorio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Relatório'),
        ),
    ]
