# Generated by Django 4.0.6 on 2022-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordemservico_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
